name: Android APK CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install Android SDK Components
      run: |
        export ANDROID_SDK_ROOT="/usr/local/lib/android/sdk"
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        wget -q https://dl.google.com/android/repository/commandline-tools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/latest
        rm cmdline-tools.zip
        
        if [ -d "$ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools" ]; then
          mv $ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
          rmdir $ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools/
        fi
        
        export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"

        yes | sdkmanager --licenses

        sdkmanager "platforms;android-36"
        sdkmanager "build-tools;36.0.0"
        sdkmanager "platform-tools"
        
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
